import { useDesignTokens } from "@/lib/design-tokens-store"
import { getPresetById } from "@/lib/style-preset-presets"
import ColorSection from "@/components/design-specs/color-section"
import TypographySection from "@/components/design-specs/typography-section"
import SpacingSection from "@/components/design-specs/spacing-section"
import ElevationSection from "@/components/design-specs/elevation-section"
import AccessibilitySection from "@/components/design-specs/accessibility-section"
import AppendixSection from "@/components/design-specs/appendix-section"

function SpecSection({
  id,
  title,
  pageBreak,
  children,
}: {
  id: string
  title: string
  pageBreak?: boolean
  children: React.ReactNode
}) {
  return (
    <section
      id={id}
      data-spec-section
      className={pageBreak ? "spec-page-break" : ""}
      style={{ breakBefore: pageBreak ? "page" : "auto" }}
    >
      <h2 className="mb-4 border-b border-border pb-2 text-lg font-bold tracking-tight text-foreground">
        {title}
      </h2>
      <div>{children}</div>
    </section>
  )
}

export default function DesignSpecs() {
  const state = useDesignTokens()
  const preset = getPresetById(state.stylePreset.activePreset)
  const harmony = state.harmonyType
  const primary = state.tokens.light.primary

  const handlePrint = () => window.print()

  return (
    <div
      data-spec-view
      className="h-full overflow-y-auto bg-background text-foreground"
      style={{ fontFamily: state.fonts.body ?? "Inter" }}
    >
      <div
        data-spec-no-print
        className="sticky top-0 z-20 flex flex-wrap items-center justify-between gap-3 border-b border-border bg-background px-6 py-4"
      >
        <div>
          <p className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">
            Print-Ready Spec
          </p>
          <h1
            className="mt-1 text-2xl font-bold tracking-tight text-foreground sm:text-3xl"
            style={{ fontFamily: state.fonts.display ?? "Archivo Narrow" }}
          >
            Design Specs
          </h1>
          <p className="mt-1 text-xs text-muted-foreground">
            {preset?.name ?? "Custom"} theme · {harmony} harmony · {primary}
          </p>
          <p className="mt-1 text-[11px] text-muted-foreground/70">
            Static, light-locked design specification. Print or export to PDF to share or hand off.
          </p>
        </div>
        <button
          onClick={handlePrint}
          className="rounded-md border bg-card px-3 py-1.5 text-xs font-semibold text-foreground transition-colors hover:bg-muted focus-visible:ring-2 focus-visible:ring-ring focus-visible:outline-none"
        >
          Export PDF
        </button>
      </div>

      <div
        className="mx-auto max-w-3xl px-6 py-10 sm:px-8 sm:py-12"
        style={{ fontFamily: state.fonts.body ?? "Inter" }}
      >
        <div className="space-y-12">
          <SpecSection id="colors" title="Color tokens" pageBreak>
            <ColorSection />
          </SpecSection>

          <SpecSection id="typography" title="Typography" pageBreak>
            <TypographySection />
          </SpecSection>

          <SpecSection id="spacing" title="Spacing & radius" pageBreak>
            <SpacingSection />
          </SpecSection>

          <SpecSection id="elevation" title="Elevation">
            <ElevationSection />
          </SpecSection>

          <SpecSection id="accessibility" title="Accessibility report" pageBreak>
            <AccessibilitySection />
          </SpecSection>

          <SpecSection id="appendix" title="Export appendix">
            <AppendixSection />
          </SpecSection>
        </div>

        <footer className="mt-12 border-t border-border pt-5 text-center font-mono text-[10px] text-muted-foreground">
          Generated by Aliya Design System · v0.4
        </footer>
      </div>
    </div>
  )
}
